public sealed record PersonalDetails(
  string FirstName,
  string? MiddleName,
  string? LastName,
  string Cnic,
  DateOnly? DateOfBirth,
  Gender? Gender,
  string? Nationality,
  MaritalStatus? MaritalStatus,
  string? BloodGroup);

/// The employee master: identity and personal details only. Posts, pay, leave and service events live in their own
/// tables. full_name is generated by the database (first + middle + last) and read back after saving.
public class Employee : Aggregate<EmployeeId>
{
  public const int NumberMaxLength = 30;
  public const int NameMaxLength = 100;
  public const string DefaultNationality = "Pakistani";

  public static readonly IReadOnlyList<string> BloodGroups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

  private readonly List<EmployeeContact> _contacts = new();
  private readonly List<EmployeeAddress> _addresses = new();
  private readonly List<EmployeeEmergencyContact> _emergencyContacts = new();
  private readonly List<EmployeeFamilyMember> _familyMembers = new();

  public string EmployeeNumber { get; private set; } = default!;
  /// The Identity user (login) of this employee. No database FK: users live in the Identity service.
  public Guid? UserId { get; private set; }
  public EmploymentType EmploymentType { get; private set; }
  public EmploymentMethod? EmploymentMethod { get; private set; }
  /// The project a project-based employee is paid from (Projects module not built yet, so no FK).
  public Guid? ProjectId { get; private set; }

  public string FirstName { get; private set; } = default!;
  public string? MiddleName { get; private set; }
  public string? LastName { get; private set; }
  /// Generated column (stored). Never assigned in code.
  public string? FullName { get; private set; }

  public string Cnic { get; private set; } = default!;
  public DateOnly? DateOfBirth { get; private set; }
  public Gender? Gender { get; private set; }
  public string? Nationality { get; private set; }
  public MaritalStatus? MaritalStatus { get; private set; }
  public string? BloodGroup { get; private set; }

  public RecordStatus ProfileStatus { get; private set; }
  public EmploymentStatus EmploymentStatus { get; private set; }
  public string? PhotoReference { get; private set; }

  public IReadOnlyList<EmployeeContact> Contacts => _contacts.AsReadOnly();
  public IReadOnlyList<EmployeeAddress> Addresses => _addresses.AsReadOnly();
  public IReadOnlyList<EmployeeEmergencyContact> EmergencyContacts => _emergencyContacts.AsReadOnly();
  public IReadOnlyList<EmployeeFamilyMember> FamilyMembers => _familyMembers.AsReadOnly();

  /// The name as the database will generate it, for use before the row is read back.
  public string DisplayName => FullName ?? string.Join(' ', new[] { FirstName, MiddleName, LastName }.Where(p => !string.IsNullOrWhiteSpace(p)));

  /// No longer in service: nothing about the service record changes any more except through a court-ordered reinstatement.
  public bool HasLeftService => EmploymentStatus is EmploymentStatus.Retired or EmploymentStatus.Resigned
    or EmploymentStatus.Terminated or EmploymentStatus.Deceased;

  public static Employee Create(
      EmployeeId id,
      string employeeNumber,
      PersonalDetails personal,
      EmploymentType employmentType,
      EmploymentMethod? employmentMethod,
      Guid? projectId,
      DateOnly today)
  {
    var employee = new Employee
    {
      Id = id,
      EmployeeNumber = NormalizeNumber(employeeNumber),
      ProfileStatus = RecordStatus.Active,
      EmploymentStatus = EmploymentStatus.Active
    };

    employee.ApplyPersonal(personal, today);
    employee.ApplyEmployment(employmentType, employmentMethod, projectId);
    return employee;
  }

  public static string NormalizeNumber(string? value) => Guard.Code(value, NumberMaxLength, "Employee number");

  public void UpdatePersonalDetails(PersonalDetails personal, DateOnly today)
  {
    EnsureProfileActive();
    ApplyPersonal(personal, today);
  }

  /// Employment type and method (regularization goes through an HR action; this is also used for corrections).
  public void ChangeEmployment(EmploymentType employmentType, EmploymentMethod? employmentMethod, Guid? projectId)
  {
    EnsureProfileActive();
    ApplyEmployment(employmentType, employmentMethod, projectId);
  }

  /// The employee number is the person's identity in every report; it changes only to correct a typing mistake.
  public void CorrectEmployeeNumber(string employeeNumber)
  {
    EnsureProfileActive();
    EmployeeNumber = NormalizeNumber(employeeNumber);
  }

  public void LinkUser(Guid userId)
  {
    if (userId == Guid.Empty)
      throw new DomainException("A user id is required.");

    UserId = userId;
  }

  public void UnlinkUser() => UserId = null;

  public void SetPhoto(string? photoReference) => PhotoReference = Guard.Text(photoReference, 500, "Photo reference");

  /// Moves the service status (on leave, suspended, deputed out, left service ...). Driven by HR actions and separations.
  public void ChangeEmploymentStatus(EmploymentStatus status)
  {
    if (status == EmploymentStatus)
      return;

    if (EmploymentStatus == EmploymentStatus.Deceased)
      throw new DomainException($"{DisplayName} is recorded as deceased; the service status cannot change.");

    EmploymentStatus = status;
  }

  /// A deactivated profile is kept for history but is no longer offered anywhere.
  public void SetProfileStatus(RecordStatus status) => ProfileStatus = status;

  public void EnsureProfileActive()
  {
    if (ProfileStatus != RecordStatus.Active)
      throw new DomainException($"The profile of {DisplayName} ({EmployeeNumber}) is inactive.");
  }

  public void EnsureInService()
  {
    EnsureProfileActive();
    if (HasLeftService)
      throw new DomainException($"{DisplayName} ({EmployeeNumber}) has left service ({EnumText.Words(EmploymentStatus)}).");
  }

  /// The date the employee reaches superannuation age (60 in KP government service).
  public DateOnly? SuperannuationDate(int retirementAge) => DateOfBirth?.AddYears(retirementAge);

  // ---- contacts: one primary per contact type ----

  public EmployeeContact AddContact(ContactType type, string value, bool isPrimary)
  {
    EnsureProfileActive();
    var contact = EmployeeContact.Create(Id, type, value);
    _contacts.Add(contact);
    if (isPrimary || !_contacts.Any(c => c.ContactType == type && c.IsPrimary))
      MakePrimary(contact);
    return contact;
  }

  public void UpdateContact(EmployeeContactId contactId, ContactType type, string value, bool isPrimary)
  {
    EnsureProfileActive();
    var contact = FindContact(contactId);
    var wasPrimary = contact.IsPrimary;
    contact.Update(type, value);

    if (isPrimary)
      MakePrimary(contact);
    else if (wasPrimary)
      contact.SetPrimary(false);
  }

  public void RemoveContact(EmployeeContactId contactId)
  {
    EnsureProfileActive();
    var contact = FindContact(contactId);
    _contacts.Remove(contact);

    // the next contact of the same type takes over as primary
    if (contact.IsPrimary && _contacts.FirstOrDefault(c => c.ContactType == contact.ContactType) is { } next)
      next.SetPrimary(true);
  }

  public string? PrimaryContact(ContactType type) => _contacts.FirstOrDefault(c => c.ContactType == type && c.IsPrimary)?.Value;

  // ---- addresses: one permanent and one current address ----

  public EmployeeAddress AddAddress(AddressType type, AddressDetails details)
  {
    EnsureProfileActive();
    EnsureSingleAddress(type, null);
    var address = EmployeeAddress.Create(Id, type, details);
    _addresses.Add(address);
    return address;
  }

  public void UpdateAddress(EmployeeAddressId addressId, AddressType type, AddressDetails details)
  {
    EnsureProfileActive();
    var address = _addresses.FirstOrDefault(a => a.Id == addressId)
      ?? throw new DomainException("The address does not belong to this employee.");
    EnsureSingleAddress(type, addressId);
    address.Update(type, details);
  }

  public void RemoveAddress(EmployeeAddressId addressId)
  {
    EnsureProfileActive();
    var address = _addresses.FirstOrDefault(a => a.Id == addressId)
      ?? throw new DomainException("The address does not belong to this employee.");
    _addresses.Remove(address);
  }

  // ---- emergency contacts and family ----

  public EmployeeEmergencyContact AddEmergencyContact(string name, string? relation, string? phone)
  {
    EnsureProfileActive();
    var contact = EmployeeEmergencyContact.Create(Id, name, relation, phone);
    _emergencyContacts.Add(contact);
    return contact;
  }

  public void UpdateEmergencyContact(EmergencyContactId contactId, string name, string? relation, string? phone)
  {
    EnsureProfileActive();
    var contact = _emergencyContacts.FirstOrDefault(c => c.Id == contactId)
      ?? throw new DomainException("The emergency contact does not belong to this employee.");
    contact.Update(name, relation, phone);
  }

  public void RemoveEmergencyContact(EmergencyContactId contactId)
  {
    EnsureProfileActive();
    var contact = _emergencyContacts.FirstOrDefault(c => c.Id == contactId)
      ?? throw new DomainException("The emergency contact does not belong to this employee.");
    _emergencyContacts.Remove(contact);
  }

  public EmployeeFamilyMember AddFamilyMember(FamilyMemberDetails details, DateOnly today)
  {
    EnsureProfileActive();
    var member = EmployeeFamilyMember.Create(Id, details, today);
    _familyMembers.Add(member);
    return member;
  }

  public void UpdateFamilyMember(FamilyMemberId memberId, FamilyMemberDetails details, DateOnly today)
  {
    EnsureProfileActive();
    var member = _familyMembers.FirstOrDefault(m => m.Id == memberId)
      ?? throw new DomainException("The family member does not belong to this employee.");
    member.Update(details, today);
  }

  public void RemoveFamilyMember(FamilyMemberId memberId)
  {
    EnsureProfileActive();
    var member = _familyMembers.FirstOrDefault(m => m.Id == memberId)
      ?? throw new DomainException("The family member does not belong to this employee.");
    _familyMembers.Remove(member);
  }

  private void MakePrimary(EmployeeContact contact)
  {
    foreach (var other in _contacts.Where(c => c.ContactType == contact.ContactType && c.Id != contact.Id && c.IsPrimary))
      other.SetPrimary(false);
    contact.SetPrimary(true);
  }

  private EmployeeContact FindContact(EmployeeContactId contactId) =>
      _contacts.FirstOrDefault(c => c.Id == contactId) ?? throw new DomainException("The contact does not belong to this employee.");

  private void EnsureSingleAddress(AddressType type, EmployeeAddressId? self)
  {
    if ((type is AddressType.Permanent or AddressType.Current) && _addresses.Any(a => a.AddressType == type && a.Id != self))
      throw new DomainException($"{DisplayName} already has a {type.ToString().ToLowerInvariant()} address. Update it instead.");
  }

  private void ApplyPersonal(PersonalDetails personal, DateOnly today)
  {
    ArgumentNullException.ThrowIfNull(personal);

    FirstName = Guard.RequiredText(personal.FirstName, NameMaxLength, "First name");
    MiddleName = Guard.Text(personal.MiddleName, NameMaxLength, "Middle name");
    LastName = Guard.Text(personal.LastName, NameMaxLength, "Last name");
    Cnic = global::Cnic.Normalize(personal.Cnic);

    if (personal.DateOfBirth is { } dob && dob >= today)
      throw new DomainException("Date of birth must be in the past.");
    DateOfBirth = personal.DateOfBirth;

    Gender = personal.Gender;
    Nationality = Guard.Text(personal.Nationality, 60, "Nationality") ?? DefaultNationality;
    MaritalStatus = personal.MaritalStatus;
    BloodGroup = NormalizeBloodGroup(personal.BloodGroup);
  }

  private void ApplyEmployment(EmploymentType employmentType, EmploymentMethod? employmentMethod, Guid? projectId)
  {
    if (employmentType == EmploymentType.Regular && employmentMethod is null)
      throw new DomainException("A regular employee needs an employment method (scheduled seat or GDA personal).");

    if (employmentType != EmploymentType.Regular && employmentMethod is not null)
      throw new DomainException("Only a regular employee has an employment method.");

    EmploymentType = employmentType;
    EmploymentMethod = employmentMethod;
    ProjectId = projectId == Guid.Empty ? null : projectId;
  }

  private static string? NormalizeBloodGroup(string? value)
  {
    if (string.IsNullOrWhiteSpace(value))
      return null;

    var group = value.Trim().ToUpperInvariant().Replace(" ", string.Empty);
    if (!BloodGroups.Contains(group))
      throw new DomainException($"Blood group must be one of {string.Join(", ", BloodGroups)}.");

    return group;
  }
}

public class EmployeeContact : Entity<EmployeeContactId>
{
  public EmployeeId EmployeeId { get; private set; } = default!;
  public ContactType ContactType { get; private set; }
  public string Value { get; private set; } = default!;
  public bool IsPrimary { get; private set; }

  internal static EmployeeContact Create(EmployeeId employeeId, ContactType type, string value)
  {
    var contact = new EmployeeContact { Id = EmployeeContactId.New(), EmployeeId = employeeId };
    contact.Update(type, value);
    return contact;
  }

  internal void Update(ContactType type, string value)
  {
    ContactType = type;
    Value = Normalize(type, value);
  }

  internal void SetPrimary(bool isPrimary) => IsPrimary = isPrimary;

  private static string Normalize(ContactType type, string value)
  {
    var text = Guard.RequiredText(value, 150, "Contact");

    if (type == ContactType.Email)
    {
      text = text.ToLowerInvariant();
      var at = text.IndexOf('@');
      if (at <= 0 || at != text.LastIndexOf('@') || !text[(at + 1)..].Contains('.') || text.Any(char.IsWhiteSpace))
        throw new DomainException($"'{text}' is not an email address.");
      return text;
    }

    if (type is ContactType.Mobile or ContactType.Phone or ContactType.Whatsapp)
    {
      var digits = text.Count(char.IsAsciiDigit);
      if (digits < 7 || digits > 15 || text.Any(c => !(char.IsAsciiDigit(c) || c is '+' or '-' or ' ' or '(' or ')')))
        throw new DomainException($"'{text}' is not a phone number (digits, spaces, '+', '-' and brackets only).");
    }

    return text;
  }
}

public sealed record AddressDetails(string? AddressLine, string? City, string? District, string? Province, string? PostalCode);

public class EmployeeAddress : Entity<EmployeeAddressId>
{
  public EmployeeId EmployeeId { get; private set; } = default!;
  public AddressType AddressType { get; private set; }
  public string? AddressLine { get; private set; }
  public string? City { get; private set; }
  public string? District { get; private set; }
  public string? Province { get; private set; }
  public string? PostalCode { get; private set; }

  internal static EmployeeAddress Create(EmployeeId employeeId, AddressType type, AddressDetails details)
  {
    var address = new EmployeeAddress { Id = EmployeeAddressId.New(), EmployeeId = employeeId };
    address.Update(type, details);
    return address;
  }

  internal void Update(AddressType type, AddressDetails details)
  {
    ArgumentNullException.ThrowIfNull(details);

    AddressType = type;
    AddressLine = Guard.Text(details.AddressLine, 300, "Address");
    City = Guard.Text(details.City, 100, "City");
    District = Guard.Text(details.District, 100, "District");
    Province = Guard.Text(details.Province, 100, "Province");
    PostalCode = Guard.Text(details.PostalCode, 20, "Postal code");

    if (AddressLine is null && City is null && District is null)
      throw new DomainException("An address needs at least an address line, a city or a district.");
  }
}

public class EmployeeEmergencyContact : Entity<EmergencyContactId>
{
  public EmployeeId EmployeeId { get; private set; } = default!;
  public string Name { get; private set; } = default!;
  public string? Relation { get; private set; }
  public string? Phone { get; private set; }

  internal static EmployeeEmergencyContact Create(EmployeeId employeeId, string name, string? relation, string? phone)
  {
    var contact = new EmployeeEmergencyContact { Id = EmergencyContactId.New(), EmployeeId = employeeId };
    contact.Update(name, relation, phone);
    return contact;
  }

  internal void Update(string name, string? relation, string? phone)
  {
    Name = Guard.RequiredText(name, 150, "Name");
    Relation = Guard.Text(relation, 60, "Relation");
    Phone = Guard.Text(phone, 30, "Phone");
  }
}

public sealed record FamilyMemberDetails(string? Relation, string? Name, DateOnly? DateOfBirth, string? Cnic, string? Occupation);

public class EmployeeFamilyMember : Entity<FamilyMemberId>
{
  public EmployeeId EmployeeId { get; private set; } = default!;
  public string? Relation { get; private set; }
  public string? Name { get; private set; }
  public DateOnly? DateOfBirth { get; private set; }
  public string? Cnic { get; private set; }
  public string? Occupation { get; private set; }

  internal static EmployeeFamilyMember Create(EmployeeId employeeId, FamilyMemberDetails details, DateOnly today)
  {
    var member = new EmployeeFamilyMember { Id = FamilyMemberId.New(), EmployeeId = employeeId };
    member.Update(details, today);
    return member;
  }

  internal void Update(FamilyMemberDetails details, DateOnly today)
  {
    ArgumentNullException.ThrowIfNull(details);

    Relation = Guard.Text(details.Relation, 60, "Relation");
    Name = Guard.Text(details.Name, 150, "Name");
    Occupation = Guard.Text(details.Occupation, 100, "Occupation");
    Cnic = global::Cnic.NormalizeOptional(details.Cnic, "Family member's CNIC");

    if (details.DateOfBirth is { } dob && dob > today)
      throw new DomainException("A family member's date of birth cannot be in the future.");
    DateOfBirth = details.DateOfBirth;

    if (Name is null && Relation is null)
      throw new DomainException("A family member needs at least a name or a relation.");
  }
}
